const componentsTable = [
  {
    idmercado: '174',
    mercado: 'Choco',
    nt_pro: '1 - 50',
    component_g: [{value: "g", cpte_publicado: 500, cpte_calculado: 500, cpte_diferencia: 0}],
    component_t: [{value: "t", cpte_publicado: 550, cpte_calculado: 500, cpte_diferencia: 50}],
    component_p: [{value: "p", cpte_publicado: 500, cpte_calculado: 500, cpte_diferencia: 0}],
    component_dtun: [{value: "dtun", cpte_publicado: 550, cpte_calculado: 500, cpte_diferencia: 50}],
    component_r: [{value: "r", cpte_publicado: 500, cpte_calculado: 500, cpte_diferencia: 0}],
    component_c: [{value: "c", cpte_publicado: 500, cpte_calculado: 500, cpte_diferencia: 0}],
    component_cu: [{value: "cu", cpte_publicado: 500, cpte_calculado: 500, cpte_diferencia: 0}]
  },
  {
    idmercado: '175',
    mercado: 'Bogotá',
    nt_pro: '1 - 50',
    component_g: [{value: "g", cpte_publicado: 500, cpte_calculado: 550, cpte_diferencia: 50}],
    component_t: [{value: "t", cpte_publicado: 550, cpte_calculado: 500, cpte_diferencia: 50}],
    component_p: [{value: "p", cpte_publicado: 500, cpte_calculado: 500, cpte_diferencia: 0}],
    component_dtun: [{value: "dtun", cpte_publicado: 550, cpte_calculado: 500, cpte_diferencia: 50}],
    component_r: [{value: "r", cpte_publicado: 500, cpte_calculado: 500, cpte_diferencia: 0}],
    component_c: [{value: "c", cpte_publicado: 500, cpte_calculado: 500, cpte_diferencia: 0}],
    component_cu: [{value: "cu", cpte_publicado: 500, cpte_calculado: 500, cpte_diferencia: 0}]
  },
  {
    idmercado: '176',
    mercado: 'Cali',
    nt_pro: '1 - 50',
    component_g: [{value: "g", cpte_publicado: 500, cpte_calculado: 500, cpte_diferencia: 0}],
    component_t: [{value: "t", cpte_publicado: 550, cpte_calculado: 500, cpte_diferencia: 50}],
    component_p: [{value: "p", cpte_publicado: 500, cpte_calculado: 500, cpte_diferencia: 0}],
    component_dtun: [{value: "dtun", cpte_publicado: 550, cpte_calculado: 500, cpte_diferencia: 50}],
    component_r: [{value: "r", cpte_publicado: 500, cpte_calculado: 500, cpte_diferencia: 0}],
    component_c: [{value: "c", cpte_publicado: 500, cpte_calculado: 500, cpte_diferencia: 0}],
    component_cu: [{value: "cu", cpte_publicado: 500, cpte_calculado: 500, cpte_diferencia: 0}]
  },
  {
    idmercado: '177',
    mercado: 'Medellin',
    nt_pro: '1 - 100',
    component_g: [{value: "g", cpte_publicado: 500, cpte_calculado: 500, cpte_diferencia: 0}],
    component_t: [{value: "t", cpte_publicado: 550, cpte_calculado: 500, cpte_diferencia: 50}],
    component_p: [{value: "p", cpte_publicado: 500, cpte_calculado: 500, cpte_diferencia: 0}],
    component_dtun: [{value: "dtun", cpte_publicado: 550, cpte_calculado: 500, cpte_diferencia: 50}],
    component_r: [{value: "r", cpte_publicado: 550, cpte_calculado: 500, cpte_diferencia: 50}],
    component_c: [{value: "c", cpte_publicado: 500, cpte_calculado: 500, cpte_diferencia: 0}],
    component_cu: [{value: "cu", cpte_publicado: 500, cpte_calculado: 500, cpte_diferencia: 0}]
  },
  {
    idmercado: '178',
    mercado: 'Cartagena',
    nt_pro: '1 - 50',
    component_g: [{value: "g", cpte_publicado: 550, cpte_calculado: 500, cpte_diferencia: 50}],
    component_t: [{value: "t", cpte_publicado: 550, cpte_calculado: 500, cpte_diferencia: 50}],
    component_p: [{value: "p", cpte_publicado: 550, cpte_calculado: 500, cpte_diferencia: 50}],
    component_dtun: [{value: "dtun", cpte_publicado: 550, cpte_calculado: 500, cpte_diferencia: 50}],
    component_r: [{value: "r", cpte_publicado: 550, cpte_calculado: 500, cpte_diferencia: 50}],
    component_c: [{value: "c", cpte_publicado: 550, cpte_calculado: 500, cpte_diferencia: 50}],
    component_cu: [{value: "cu", cpte_publicado: 500, cpte_calculado: 500, cpte_diferencia: 0}]
  },
  {
    idmercado: '178',
    mercado: 'Cartagena',
    nt_pro: '1 - 50',
    component_g: [{value: "g", cpte_publicado: 550, cpte_calculado: 500, cpte_diferencia: 50}],
    component_t: [{value: "t", cpte_publicado: 550, cpte_calculado: 500, cpte_diferencia: 50}],
    component_p: [{value: "p", cpte_publicado: 550, cpte_calculado: 500, cpte_diferencia: 50}],
    component_dtun: [{value: "dtun", cpte_publicado: 550, cpte_calculado: 500, cpte_diferencia: 50}],
    component_r: [{value: "r", cpte_publicado: 550, cpte_calculado: 500, cpte_diferencia: 50}],
    component_c: [{value: "c", cpte_publicado: 550, cpte_calculado: 500, cpte_diferencia: 50}],
    component_cu: [{value: "cu", cpte_publicado: 500, cpte_calculado: 500, cpte_diferencia: 0}]
  },
  {
    idmercado: '178',
    mercado: 'Cartagena',
    nt_pro: '1 - 50',
    component_g: [{value: "g", cpte_publicado: 550, cpte_calculado: 500, cpte_diferencia: 50}],
    component_t: [{value: "t", cpte_publicado: 550, cpte_calculado: 500, cpte_diferencia: 50}],
    component_p: [{value: "p", cpte_publicado: 550, cpte_calculado: 500, cpte_diferencia: 50}],
    component_dtun: [{value: "dtun", cpte_publicado: 550, cpte_calculado: 500, cpte_diferencia: 50}],
    component_r: [{value: "r", cpte_publicado: 550, cpte_calculado: 500, cpte_diferencia: 50}],
    component_c: [{value: "c", cpte_publicado: 550, cpte_calculado: 500, cpte_diferencia: 50}],
    component_cu: [{value: "cu", cpte_publicado: 500, cpte_calculado: 500, cpte_diferencia: 0}]
  },
  {
    idmercado: '178',
    mercado: 'Cartagena',
    nt_pro: '1 - 50',
    component_g: [{value: "g", cpte_publicado: 550, cpte_calculado: 500, cpte_diferencia: 50}],
    component_t: [{value: "t", cpte_publicado: 550, cpte_calculado: 500, cpte_diferencia: 50}],
    component_p: [{value: "p", cpte_publicado: 550, cpte_calculado: 500, cpte_diferencia: 50}],
    component_dtun: [{value: "dtun", cpte_publicado: 550, cpte_calculado: 500, cpte_diferencia: 50}],
    component_r: [{value: "r", cpte_publicado: 550, cpte_calculado: 500, cpte_diferencia: 50}],
    component_c: [{value: "c", cpte_publicado: 550, cpte_calculado: 500, cpte_diferencia: 50}],
    component_cu: [{value: "cu", cpte_publicado: 500, cpte_calculado: 500, cpte_diferencia: 0}]
  },
  {
    idmercado: '178',
    mercado: 'Cartagena',
    nt_pro: '1 - 50',
    component_g: [{value: "g", cpte_publicado: 550, cpte_calculado: 500, cpte_diferencia: 50}],
    component_t: [{value: "t", cpte_publicado: 550, cpte_calculado: 500, cpte_diferencia: 50}],
    component_p: [{value: "p", cpte_publicado: 550, cpte_calculado: 500, cpte_diferencia: 50}],
    component_dtun: [{value: "dtun", cpte_publicado: 550, cpte_calculado: 500, cpte_diferencia: 50}],
    component_r: [{value: "r", cpte_publicado: 550, cpte_calculado: 500, cpte_diferencia: 50}],
    component_c: [{value: "c", cpte_publicado: 550, cpte_calculado: 500, cpte_diferencia: 50}],
    component_cu: [{value: "cu", cpte_publicado: 500, cpte_calculado: 500, cpte_diferencia: 0}]
  },
  {
    idmercado: '178',
    mercado: 'Cartagena',
    nt_pro: '1 - 50',
    component_g: [{value: "g", cpte_publicado: 550, cpte_calculado: 500, cpte_diferencia: 50}],
    component_t: [{value: "t", cpte_publicado: 550, cpte_calculado: 500, cpte_diferencia: 50}],
    component_p: [{value: "p", cpte_publicado: 550, cpte_calculado: 500, cpte_diferencia: 50}],
    component_dtun: [{value: "dtun", cpte_publicado: 550, cpte_calculado: 500, cpte_diferencia: 50}],
    component_r: [{value: "r", cpte_publicado: 550, cpte_calculado: 500, cpte_diferencia: 50}],
    component_c: [{value: "c", cpte_publicado: 550, cpte_calculado: 500, cpte_diferencia: 50}],
    component_cu: [{value: "cu", cpte_publicado: 500, cpte_calculado: 500, cpte_diferencia: 0}]
  },
  {
    idmercado: '178',
    mercado: 'Cartagena',
    nt_pro: '1 - 50',
    component_g: [{value: "g", cpte_publicado: 550, cpte_calculado: 500, cpte_diferencia: 50}],
    component_t: [{value: "t", cpte_publicado: 550, cpte_calculado: 500, cpte_diferencia: 50}],
    component_p: [{value: "p", cpte_publicado: 550, cpte_calculado: 500, cpte_diferencia: 50}],
    component_dtun: [{value: "dtun", cpte_publicado: 550, cpte_calculado: 500, cpte_diferencia: 50}],
    component_r: [{value: "r", cpte_publicado: 550, cpte_calculado: 500, cpte_diferencia: 50}],
    component_c: [{value: "c", cpte_publicado: 550, cpte_calculado: 500, cpte_diferencia: 50}],
    component_cu: [{value: "cu", cpte_publicado: 500, cpte_calculado: 500, cpte_diferencia: 0}]
  },
  {
    idmercado: '178',
    mercado: 'Cartagena',
    nt_pro: '1 - 50',
    component_g: [{value: "g", cpte_publicado: 550, cpte_calculado: 500, cpte_diferencia: 50}],
    component_t: [{value: "t", cpte_publicado: 550, cpte_calculado: 500, cpte_diferencia: 50}],
    component_p: [{value: "p", cpte_publicado: 550, cpte_calculado: 500, cpte_diferencia: 50}],
    component_dtun: [{value: "dtun", cpte_publicado: 550, cpte_calculado: 500, cpte_diferencia: 50}],
    component_r: [{value: "r", cpte_publicado: 550, cpte_calculado: 500, cpte_diferencia: 50}],
    component_c: [{value: "c", cpte_publicado: 550, cpte_calculado: 500, cpte_diferencia: 50}],
    component_cu: [{value: "cu", cpte_publicado: 500, cpte_calculado: 500, cpte_diferencia: 0}]
  },
  {
    idmercado: '178',
    mercado: 'Cartagena',
    nt_pro: '1 - 50',
    component_g: [{value: "g", cpte_publicado: 550, cpte_calculado: 500, cpte_diferencia: 50}],
    component_t: [{value: "t", cpte_publicado: 550, cpte_calculado: 500, cpte_diferencia: 50}],
    component_p: [{value: "p", cpte_publicado: 550, cpte_calculado: 500, cpte_diferencia: 50}],
    component_dtun: [{value: "dtun", cpte_publicado: 550, cpte_calculado: 500, cpte_diferencia: 50}],
    component_r: [{value: "r", cpte_publicado: 550, cpte_calculado: 500, cpte_diferencia: 50}],
    component_c: [{value: "c", cpte_publicado: 550, cpte_calculado: 500, cpte_diferencia: 50}],
    component_cu: [{value: "cu", cpte_publicado: 500, cpte_calculado: 500, cpte_diferencia: 0}]
  },
  {
    idmercado: '178',
    mercado: 'Cartagena',
    nt_pro: '1 - 50',
    component_g: [{value: "g", cpte_publicado: 550, cpte_calculado: 500, cpte_diferencia: 50}],
    component_t: [{value: "t", cpte_publicado: 550, cpte_calculado: 500, cpte_diferencia: 50}],
    component_p: [{value: "p", cpte_publicado: 550, cpte_calculado: 500, cpte_diferencia: 50}],
    component_dtun: [{value: "dtun", cpte_publicado: 550, cpte_calculado: 500, cpte_diferencia: 50}],
    component_r: [{value: "r", cpte_publicado: 550, cpte_calculado: 500, cpte_diferencia: 50}],
    component_c: [{value: "c", cpte_publicado: 550, cpte_calculado: 500, cpte_diferencia: 50}],
    component_cu: [{value: "cu", cpte_publicado: 500, cpte_calculado: 500, cpte_diferencia: 0}]
  },
]

export default componentsTable
